apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-secret.yaml
  - db-deployment.yaml
  - db-service.yaml
  - db-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
